# --- Base de données MongoDB ---
quarkus.mongodb.connection-string=${MONGODB_URI:mongodb://localhost:27017}
quarkus.mongodb.database=destimatch

# --- Configuration HTTP & CORS ---
# Le port pour le mode dev
%dev.quarkus.http.port=3000

# --- CORS ---
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

quarkus.log.level=INFO
quarkus.log.category."io.quarkus.rest.jackson".level=DEBUG
quarkus.log.category."io.quarkus.mongodb.panache".level=DEBUG

# --- JSON Configuration ---
quarkus.jackson.property-naming-strategy=SNAKE_CASE

# --- TRANSACTION ---
quarkus.transaction-manager.default-transaction-timeout=3000s

mp.jwt.verify.issuer=https://destimatch.com
smallrye.jwt.sign.key.location=classpath:privateKey.pem
mp.jwt.verify.publickey.location=classpath:publicKey.pem
smallrye.jwt.new-token.signature-algorithm=RS256

# --- CONFIG APPLICATION ---
destimatch.admin.secret=SuperSecretKey2026!