quarkus.mongodb.connection-string=${MONGODB_URI:mongodb://localhost:27017}
quarkus.mongodb.database=destimatch

# --- Configuration HTTP & CORS ---
# Le port pour le mode dev
%dev.quarkus.http.port=8082

# --- CORS ---
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-allow-credentials=true

quarkus.log.level=INFO
quarkus.log.category."io.quarkus.rest.jackson".level=DEBUG
quarkus.log.category."io.quarkus.mongodb.panache".level=DEBUG

# --- JSON Configuration ---
quarkus.jackson.property-naming-strategy=SNAKE_CASE

# --- TRANSACTION ---
# quarkus.transaction-manager.default-transaction-timeout=3000s

mp.jwt.verify.issuer=https://destimatch.com
smallrye.jwt.sign.key.location=classpath:privateKey.pem
mp.jwt.verify.publickey.location=classpath:publicKey.pem
smallrye.jwt.new-token.signature-algorithm=RS256

# --- CONFIG APPLICATION ---
destimatch.admin.secret=SuperSecretKey2026!

# --- GEMINI AI ---
quarkus.rest-client.gemini-api.url=https://generativelanguage.googleapis.com
quarkus.rest-client.gemini-api.scope=jakarta.inject.Singleton

gemini.api.key=${GEMINI_API_KEY}